print('Test Program')
print('Purposeful error')
